export const BUSINESS_HOURS = {
    START: '08:30',
    END: '17:30',
} as const;

export const WORKING_DAYS = [1, 2, 3, 4, 5] as const; // Monday to Friday

export const SLOT_DURATION_MINUTES = 30;

export const MAX_BOOKING_WEEKS = 8;

export const DEFAULT_PRICING = {
    car: 90,
    bus: 110,
    motorcycle: 60,
    taxi: 60,
    caravan: 60,
    hanger: 60,
    lpg: 45,
} as const;

export const VEHICLE_BRANDS = [
    'BAIC',
    'BAW',
    'BMW',
    'BYD',
    'AC',
    'Abarth',
    'Acura',
    'Aixam',
    'Alfa Romeo',
    'Alpina',
    'Aro',
    'Asia',
    'Aston Martin',
    'Audi',
    'Austin',
    'Bentley',
    'Bertone',
    'Brilliance',
    'Buick',
    'Cadillac',
    'Carbodies',
    'Changan',
    'Chery',
    'Chevrolet',
    'Chrysler',
    'Citroen',
    'Corvette',
    'Cupra',
    'DFSK',
    'DONGFENG',
    'DR Automobiles',
    'DS',
    'Dacia',
    'Daewoo',
    'Daihatsu',
    'Daimler',
    'Datsun',
    'Dkw',
    'Dodge',
    'Dr',
    'Други',
    'Ferrari',
    'Fiat',
    'Ford',
    'Foton',
    'GOUPIL',
    'GWM',
    'Gaz',
    'Geely',
    'Genesis',
    'Gmc',
    'Gonow',
    'Great Wall',
    'Haval',
    'Honda',
    'HongQi',
    'Hummer',
    'Hyundai',
    'Ifa',
    'Ineos Grenadier',
    'Infiniti',
    'Isuzu',
    'Iveco',
    'JAC',
    'Jaguar',
    'Jeep',
    'Kia',
    'Lada',
    'Lamborghini',
    'Lancia',
    'Land Rover',
    'Landwind',
    'Lexus',
    'Lincoln',
    'Lotus',
    'LynkCo',
    'Mahindra',
    'Maserati',
    'Maybach',
    'Mazda',
    'McLaren',
    'Mercedes-Benz',
    'Mercury',
    'Mg',
    'Microcar',
    'Microlino',
    'Mini',
    'Mitsubishi',
    'Morgan',
    'Moskvich',
    'Nissan',
    'Oldsmobile',
    'Opel',
    'Peugeot',
    'Plymouth',
    'Polestar',
    'Pontiac',
    'Porsche',
    'Renault',
    'Rolls-Royce',
    'Rover',
    'SECMA',
    'SIN CARS',
    'SWM',
    'Saab',
    'Scion',
    'Seat',
    'Seres',
    'Shuanghuan',
    'Simca',
    'Skoda',
    'Smart',
    'SsangYong',
    'Subaru',
    'Suzuki',
    'Talbot',
    'Tata',
    'Tazzari',
    'Tesla',
    'Toyota',
    'Trabant',
    'Triumph',
    'Uaz',
    'VW',
    'Volga',
    'Volvo',
    'Voyah',
    'Warszawa',
    'Wartburg',
    'Wey',
    'Zaz',
];

export const MOTORCYCLE_BRANDS = [
    'ADLI',
    'Aeon',
    'American Ironhorse',
    'Aprilia',
    'Arctic Cat',
    'Argo',
    'Askoll',
    'Awo',
    'BMW',
    'BRP',
    'Balkan',
    'Baotian',
    'Barton',
    'Bashan',
    'Benelli',
    'Benzhou',
    'Beta',
    'Big Dog',
    'Bombardier',
    'Boss Hoss',
    'Brixton',
    'Buell',
    'Buyang',
    'Cagiva',
    'Can-Am',
    'Cfmoto',
    'Cpi',
    'Cz',
    'Daelim',
    'Daytona',
    'Derbi',
    'Dinli',
    'Ducati',
    'Etz',
    'FB Mondial',
    'Falcon',
    'Fantic',
    'GASGAS',
    'Garelli',
    'Generic',
    'Gilera',
    'Go-ped',
    'HISUN',
    'Hanway',
    'Harley-Davidson',
    'Honda',
    'Horwin',
    'Husaberg',
    'Husqvarna',
    'Hyosung',
    'Indian',
    'Italjet',
    'Jawa',
    'Jinlun',
    'Jonway',
    'KSR',
    'Kawasaki',
    'Keeway',
    'Kinetic',
    'Ktm',
    'Kymco',
    'La Souris',
    'Lambreta',
    'Lexmoto',
    'Lifan',
    'Ligier',
    'Linhai',
    'Lynx',
    'MV Agusta',
    'Malaguti',
    'Mbk',
    'Moto Guzzi',
    'Moto Morini',
    'MotorHispania',
    'Motoretta',
    'Mz',
    'NIU',
    'Orcal',
    'Peugeot',
    'Piaggio',
    'Polaris',
    'Puch',
    'QJMotor',
    'Qingqi',
    'Quadro',
    'Revolt',
    'Rieju',
    'Romet',
    'Royal Enfield',
    'Sachs',
    'Segway Powersports',
    'Sherco',
    'Shineray',
    'Silence',
    'Simson',
    'Ski-Doo',
    'Stark',
    'Sunsto',
    'Super Soco',
    'Surron',
    'Suzuki',
    'Swm',
    'Sym',
    'Telstar',
    'Tgb',
    'Tm',
    'Tomos',
    'Triumph',
    'VROMOS',
    'Vespa',
    'Victory',
    'Voge',
    'Volta',
    'Wt',
    'XGJao',
    'Xingyue',
    'Yamaha',
    'Yawa',
    'Zero',
    'Znen',
    'Zongshen',
    'Zontes',
    'Zundapp',
    'iO Scooter',
    'Други',
    'Днепр',
    'Иж',
    'Карпати',
    'Ковровец',
    'Мини мотоциклети',
    'Минск',
    'Поръчкови',
    'Рига',
] as const;

export const BUS_BRANDS = [
    'Avia',
    'Ayats',
    'BMC',
    'BYD',
    'Barkas',
    'Bedford',
    'Bova',
    'Chavdar',
    'Chevrolet',
    'Citroen',
    'Daewoo',
    'DONGFENG',
    'Fiat',
    'Ford',
    'Gaz',
    'Gmc',
    'Hyundai',
    'Ikarus',
    'Irizar',
    'Isuzu',
    'Iveco',
    'Jonckheere',
    'Karsan',
    'Kia',
    'King Long',
    'L CITY',
    'LDV',
    'Man',
    'Mazda',
    'Mercedes-Benz',
    'Mitsubishi',
    'Neoplan',
    'Nissan',
    'Opel',
    'Otokar',
    'Peugeot',
    'Piaggio',
    'Renault',
    'Robur',
    'Scania',
    'Setra',
    'Solaris',
    'Suzuki',
    'VW',
] as const;
